export enum AthleteColumn {
    id            = 'id',
    athleteCode   = 'athleteCode',
    firstName     = 'firstName',
    lastName      = 'lastName',
    gender        = 'gender',
    age           = 'age',
    dateOfBirth   = 'dateOfBirth',
    country       = 'country',
    sport         = 'sport',
    position      = 'position',
    team          = 'team',
    ranking       = 'ranking',
    medals        = 'medals',
    matchesPlayed = 'matchesPlayed',
    wins          = 'wins',
    losses        = 'losses',
    winRate       = 'winRate',
    heightCm      = 'heightCm',
    weightKg      = 'weightKg',
    yearsPro      = 'yearsPro',
    salaryUsd     = 'salaryUsd',
    isOlympian    = 'isOlympian',
    status        = 'status',
    lastUpdated   = 'lastUpdated',
}

export enum AthleteColumnLabel {
    id            = 'Id',
    athleteCode   = 'Code',
    firstName     = 'First Name',
    lastName      = 'Last Name',
    gender        = 'Gender',
    age           = 'Age',
    dateOfBirth   = 'Date of Birth',
    country       = 'Country',
    sport         = 'Sport',
    position      = 'Position',
    team          = 'Team',
    ranking       = 'Ranking',
    medals        = 'Medals',
    matchesPlayed = 'Matches',
    wins          = 'Wins',
    losses        = 'Losses',
    winRate       = 'Win Rate',
    heightCm      = 'Height (cm)',
    weightKg      = 'Weight (kg)',
    yearsPro      = 'Years Pro',
    salaryUsd     = 'Salary (USD)',
    isOlympian    = 'Olympian',
    status        = 'Status',
    lastUpdated   = 'Last Updated',
}
